# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Audrey Watters"
description: > # this means to ignore newlines until "email:"
   Writer, Rabble-rouser

email: mail@audreywatters.com
#blog logo
logo: "/assets/images/aw_logo.jpg"
# blog cover
cover: "/assets/images/notredame.jpg"

name: 'Audrey Watters'
author: 'Audrey Watters'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://dev.audreywatters.com" # the base hostname & protocol for your site
baseurl: "http://dev.audreywatters.com"

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 15
paginate_path: "/blog/page:num"

production_url : http://apievangelist.com

BASE_PATH : http://apievangelist.com

categories_path : /categories.html
tags_path : /tags.html

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/audreywatters
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/audreywatters
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
  